# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca6b4e4f0b227a796bffd3808c78c725b54fa8309fce0fc12246e66da797b51d98c2019054dea1696b4c517e19ce8962da8b864d1db39a7c3210de21836fd113

test:
  secret_key_base: 9843b361d157d68dcdf14b93a514aa0ff1edb7db9c8c93988b66d41e05790a183287937c1b5763b635c3b24358f7edb0c9411c2b993cf83c8585b518dd950e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
